### ISSUE TITLE
Cluster the config values by active state

### ISSUE THREAD

**Issue by eljobe** [eljobe/janky-shimmer#2]
Currently, the config has some top-level options which allow for configuring
things like animation timing and the list of colors which will be iterated
through. But, really, it should be possible to have entirely independent
configurations for the behavior of active and inactive windows.

As a rough sketch, maybe something like:
```toml
[[active]]
colors = []
secs = 0.75
fps = 12.0
width = 10
glow = true

[[inactive]]
colors = []
secs = 2
glow = false
```

It would also be great to figure out a way to make it clear to users that if
`[[inactive]]` isn't specified that inactive windows will inherit the values
from `[[active]]` and that if `[[inactive]]` specifies fewer fields, that the
other fields will also be inherited from the `[[active]]` config.
